/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#00113a",
        secondary: "#4b53bc",
        "primary-container": "#002366",
        "secondary-container": "#8991fe",
        "on-secondary-container": "#1b218f",
        "outline-variant": "#c5c6d2",
        "on-surface-variant": "#444650",
        "inverse-surface": "#2f3035",
        background: "#faf8ff",
        surface: "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f9",
        "surface-container": "#efedf3",
        "surface-container-high": "#e9e7ee",
        "surface-container-highest": "#e3e2e8",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b3c5ff",
        "on-primary-fixed": "#00174a",
        "on-primary-fixed-variant": "#2a4386",
        "secondary-fixed": "#e0e0ff",
        "secondary-fixed-dim": "#bfc2ff",
        "on-secondary-fixed": "#00006e",
        "on-secondary-fixed-variant": "#3239a3",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59e",
        "on-tertiary-fixed": "#390b00",
        "on-tertiary-fixed-variant": "#783018",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface": "#1a1b20",
        "on-background": "#1a1b20",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        /* ===== LUXURY PALETTE ===== */
        ink: "#070A10",
        "ink-800": "#0A0F18",
        "ink-700": "#101722",
        "ink-600": "#172331",
        "ink-soft": "#202D3B",
        gold: "#20BCEB",
        "gold-light": "#9AE4F8",
        "gold-deep": "#058CB7",
        champagne: "#E5F7FC",
        ivory: "#FFFFFF",
        cream: "#F2F7F9",
        "luxury-muted": "#A9B5C2",
      },
      backgroundImage: {
        "gold-gradient": "linear-gradient(135deg, #058CB7 0%, #9AE4F8 45%, #20BCEB 100%)",
        "gold-sheen": "linear-gradient(120deg, #20BCEB 0%, #E5F7FC 40%, #058CB7 80%)",
        "ink-radial": "radial-gradient(ellipse at 50% 0%, #172331 0%, #070A10 60%)",
      },
      boxShadow: {
        luxe: "0 20px 60px -15px rgba(0,0,0,0.5)",
        "luxe-gold": "0 10px 40px -10px rgba(32,188,235,0.35)",
        "luxe-soft": "0 24px 70px -30px rgba(10,14,26,0.35)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        unit: "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        gutter: "24px",
        "160px": "160px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Montserrat", "Inter", "sans-serif"],
        serif: ["Montserrat", "Inter", "sans-serif"],
        cormorant: ["'Cormorant Garamond'", "serif"],
        body: ["Inter", "sans-serif"],
      },
      letterSpacing: {
        luxe: "0.25em",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.7s cubic-bezier(0.16,1,0.3,1) both",
        "fade-in": "fade-in 0.8s ease both",
        shimmer: "shimmer 3s linear infinite",
      },
    },
  },
  plugins: [],
}
